import { FileText, Receipt, Users } from 'lucide-react';

const formatAmount = (amount) => `AED ${(amount || 0).toLocaleString('en-US', { minimumFractionDigits: 2 })}`;

export default function AgentDashboard({ customers, documents, invoices, filings }) {
  const receivable = invoices.filter(invoice => !['paid', 'cancelled'].includes(invoice.status)).reduce((total, invoice) => total + (invoice.total || 0), 0);
  const expiring = documents.filter(document => document.expiry_date && new Date(document.expiry_date) <= new Date(Date.now() + 30 * 86400000)).length;
  const cards = [{ label: 'Assigned Customers', value: customers.length, icon: Users, color: 'text-blue-600 bg-blue-50' }, { label: 'Documents Expiring Soon', value: expiring, icon: FileText, color: 'text-amber-600 bg-amber-50' }, { label: 'Receivable Amount', value: formatAmount(receivable), icon: Receipt, color: 'text-green-600 bg-green-50' }];
  return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-3">{cards.map(({ label, value, icon: Icon, color }) => <div key={label} className="rounded-xl border border-gray-200 bg-white p-5"><div className={`mb-3 flex h-10 w-10 items-center justify-center rounded-lg ${color}`}><Icon className="h-5 w-5" /></div><p className="text-2xl font-bold text-gray-900">{value}</p><p className="mt-1 text-sm text-gray-500">{label}</p></div>)}</div><div className="rounded-xl border border-gray-200 bg-white"><div className="border-b border-gray-100 px-5 py-4"><h2 className="font-semibold text-gray-900">Recent Filings</h2></div>{filings.slice(0, 5).map(filing => <div key={filing.id} className="flex items-center justify-between border-b border-gray-100 px-5 py-3 last:border-0"><div><p className="text-sm font-medium text-gray-800">{filing.customer_name}</p><p className="text-xs text-gray-400">{filing.filing_month}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${filing.status === 'filed' ? 'bg-green-50 text-green-700' : 'bg-amber-50 text-amber-700'}`}>{filing.status === 'filed' ? 'Filed' : 'Draft'}</span></div>)}{!filings.length && <p className="px-5 py-10 text-center text-sm text-gray-400">No filings yet.</p>}</div></div>;
}